{
  pkgs,
  lib,
  config,
  src,
  ...
}: let
  inherit (lib) enabled' getExe;

  rclone = getExe pkgs.rclone;

  estradiol-backups-s3-bucket = "estradiol-backups-476443350685-ca-central-1-an";

  backupCleanupCommand = restic-repo: s3-bucket:
    (pkgs.writeShellScript "rclone-s3-mirror" ''
      if [ "$SERVICE_RESULT" != "success" ]; then
        echo "restic exited with $SERVICE_RESULT, skipping S3 mirror"
        exit 0
      fi
      ${rclone} copy ${restic-repo} s3backup:${s3-bucket} \
        --s3-storage-class DEEP_ARCHIVE \
        --log-level INFO
    '')
    |> toString;

  commonExcludes = [
    "**/.cache/"
    "**/.zig-out/"
    "**/.cargo/"
    "**/node_modules/"
    "**/target/"
    "/nix/store/"
    "**/pkg/mod/"

    "!.git-crypt-key"
    ".vscode/"
    ".DS_Store"
    "Thumbs.db"
    "!.envrc"
  ];
in {
  age.secrets = {
    rclone-s3 = {
      file = lib.path.append src "secrets/restic-rclone-s3-env.age";
      mode = "400";
      owner = "root";
      group = "root";
    };
    restic-password = {
      file = lib.path.append src "secrets/restic-password.age";
      mode = "400";
      owner = "jules";
      group = "root";
    };
    restic-htpasswd = {
      file = lib.path.append src "secrets/restic-htpasswd.age";
      path = "/mnt/BACKUPS/restic-server-repos/.htpasswd";
      mode = "644";
    };
  };

  local.homeSessionVariables = {
    RESTIC_REPOSITORY = "/mnt/BACKUPS/restic-repo";
    RESTIC_PASSWORD_FILE = config.age.secrets.restic-password.path;
  };

  systemd.services."restic-backups-home" = {
    serviceConfig.EnvironmentFile = config.age.secrets.rclone-s3.path;
  };

  environment.systemPackages = with pkgs; [restic restic-browser backrest];

  services.restic = {
    server = enabled' {
      dataDir = "/mnt/BACKUPS/restic-server-repos";
    };
    backups = {
      home = let
        repository = "/mnt/BACKUPS/restic-repo";
      in {
        inherit repository;
        paths = ["/home/jules"];
        passwordFile = config.age.secrets.restic-password.path;

        timerConfig = {
          OnUnitActiveSec = "14d";
          Persistent = true;
        };

        pruneOpts = [
          "--keep-daily 7"
          "--keep-weekly 4"
          "--keep-monthly 6"
        ];

        backupCleanupCommand = backupCleanupCommand repository estradiol-backups-s3-bucket;

        exclude =
          [
            # generated by nix/home-manager, skip entirely
            "/home/jules/.config"

            # steam game binaries (enormous, reinstallable)
            "/home/jules/.local/share/Steam/steamapps/common"
            "/home/jules/.local/share/Steam/steamapps/shadercache"
            "/home/jules/.local/share/Steam/steamapps/temp"

            "/home/jules/Games/Heroic"
          ]
          ++ commonExcludes;
      };
    };
  };
}
